### ISSUE TITLE
Prompt for the Fee Asset Data

### ISSUE THREAD

**Issue by dekz** [0xProject/0x-launch-kit#30]
V2 assumed ZRX was the fee asset data and no prompt was made. In V3 Fee Asset data can be any token and isn't being set in the wizard.

`MAKER_FEE_ASSET_DATA` and `TAKER_FEE_ASSET_DATA` should be set in the backend container.

Prompt for the ERC20 contract address and encode as ERC20 asset data for the golden path.

**Comment by SvenMeyer** [comment]
@dekz maybe you can already give an example how a proper value set would look like in docker-compose.yml ?

**Comment by dekz** [comment]
```yml
backend:
        image: 0xorg/launch-kit-backend:v3
        environment:
            HTTP_PORT: '3000'
            NETWORK_ID: '50'
            WHITELIST_ALL_TOKENS: 'true'
            FEE_RECIPIENT: '0x0000000000000000000000000000000000000001'
            MAKER_FEE_UNIT_AMOUNT: '1'
            TAKER_FEE_UNIT_AMOUNT: '1'
            MAKER_FEE_ASSET_DATA: '0xf47261b0000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'
            TAKER_FEE_ASSET_DATA: '0xf47261b0000000000000000000000000c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2'
            MESH_ENDPOINT: 'ws://mesh:60557'
        ports:
            - '3000:3000'
```

Should set the correct values when the order is created.
